### ISSUE TITLE
Zeiteinteilung

### ISSUE THREAD

**Issue by S-ecki** [S-ecki/smart-city-ambience#10]

**Comment by S-ecki** [comment]
Simon: 1h

**Comment by samuelm00** [comment]
3h Authentification

**Comment by S-ecki** [comment]
2h routing, theme, bottom navigation bar, appbar, base widgets for all screens, helped alex to start implementation
1,5h layout of homescreen an design
1h helping other parts
2h Pie Chart
0,5h Word Cloud
2h Bar Chart
WAY TOO LONG emotion input (fuck toggle buttons) (3h)
1,5h fixes (routing, naming, bar chart axis, refactoring, desing)
1,5h chart interactivity, word cloud state management
2h various fixes, helping other parts
1h report function, alert message on report, styling news
0,5h design changes forum/news cards
1h location slider
3h working over whole app (ui, ux)
2,5h font/theme
1h issues
1,5h final changes

**Comment by samuelm00** [comment]
4h State Management Reactions, components to react to an event

**Comment by samuelm00** [comment]
30 min Detail Screen + 2h Comment functionality

**Comment by samuelm00** [comment]
1 h Google Login
